In [6]:
import pandas as pd
import numpy as np

drivers = pd.read_csv("tables/drivers.csv")
construtors = pd.read_csv("tables/constructors.csv")
races = pd.read_csv("tables/races.csv")
results = pd.read_csv("tables/results.csv")

drivers.head(3)

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg

In [3]:
construtors.head(3)

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...

In [4]:
races.head(3)

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [5]:
results.head(3)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1

In [15]:
races_post_2014 = races[races["year"] >= 2014]
races_post_2014_replaced = races_post_2014.replace(r'\N', None)

races_post_2014_replaced.head(3)

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
897,900,2014,1,1,Australian Grand Prix,2014-03-16,06:00:00,http://en.wikipedia.org/wiki/2014_Australian_G...,None,None,None,None,None,None,None,None,None,None
898,901,2014,2,2,Malaysian Grand Prix,2014-03-30,08:00:00,http://en.wikipedia.org/wiki/2014_Malaysian_Gr...,None,None,None,None,None,None,None,None,None,None
899,902,2014,3,3,Bahrain Grand Prix,2014-04-06,15:00:00,http://en.wikipedia.org/wiki/2014_Bahrain_Gran...,None,None,None,None,None,None,None,None,None,None

In [18]:
drivers["driver_name"] = drivers[["forename", "surname"]].agg(" ".join, axis=1)
drivers.head(3)

,driverId,driverRef,number,code,forename,surname,dob,nationality,url,driver_name
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,Lewis Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,Nick Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,Nico Rosberg

In [ ]:
drivers.to_csv("clean_data/drivers_clean.csv")
races_post_2014_replaced.to_csv("clean_data/races_clean.csv")